meta:
  schema-version: 0.1.0
  created-on: "2026-07-23T10:12:55Z"
  cli-version: v0.3.291
projects:
  seal-test-npm-23-07:
    targets:
      - /Users/jenny.asealsecurity.io/SealTests/Tenant_Jenny/Local_cli_npm_23-07/package.json
    manager:
      ecosystem: node
      name: npm
      version: 10.9.3
      class: manifest
    overrides:
      axios:
        1.11.0:
          use: 1.11.0-sp1
      follow-redirects:
        1.15.6:
          use: 1.15.6-sp1
      glob-parent:
        5.1.1:
          use: 5.1.1-sp1
      js-yaml:
        3.14.1:
          use: 3.14.1-sp1
